# Generated by Django 4.1.3 on 2022-12-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draftC', 'DraftC'), ('publishedC', 'PublishedC')], default='draft', max_length=10),
        ),
    ]
